version: "3.9"

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_api
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/backend_api_db
      MONGO_DB_NAME: backend_api_db
      APP_NAME: backend_api
    depends_on:
      - mongodb
    volumes:
      - .:/app

  mongodb:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
